export const UPDATE_INCOME = "UPDATE_INCOME";
export const UPDATE_EXPENSE = "UPDATE_EXPENSE";
export const REMOVE_INCOME = "REMOVE_INCOME";
export const REMOVE_EXPENSE = "REMOVE_EXPENSE";
export const ADD_INCOME = "ADD_INCOME";
export const ADD_EXPENSE = "ADD_EXPENSE";
